apiVersion: v1
kind: ConfigMap
metadata:
  name: rajeshapp-config
  namespace: rajeshapp
  labels:
    app.kubernetes.io/name: rajeshapp
    app.kubernetes.io/part-of: rajeshapp

data:
  PORT: "8080"
  PYTHONUNBUFFERED: "1"