apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: rajeshapp-ingress
  namespace: rajeshapp

spec:
  ingressClassName: nginx

  rules:
    - host: rajeshapp.local

      http:
        paths:
          - path: /
            pathType: Prefix

            backend:
              service:
                name: rajeshapp-service
                port:
                  number: 80